version: "4.17"

services:
  db:
    image: mysql:5.7
    container_name: resheno_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - the_net

  wordpress_docker:
    depends_on:
      - db
    links:
      - db
    image: wordpress:latest
    container_name: resheno_wordpress
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - the_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: resheno_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - /resheno
    networks:
      - the_net

  gatsby-ts:
    depends_on:
      - wordpress_docker
    links: 
      - wordpress_docker
    working_dir: /app
    container_name: resheno-gatsby
    hostname: resheno-gatsby
    build:
      context: ./gatsby-resheno
      dockerfile: Dockerfile.gatsby
    command: gatsby develop -H 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
      - "3125:3125" #this is used by gatsby socket.io hot reload
    volumes:
      - ./gatsby-resheno/:/app
      - /app/node_modules
    environment:
      WORDPRESS_URL: http://wordpress_docker/index.php?graphql
      NODE_ENV: development
      INTERNAL_STATUS_PORT: 3125 #this is used by gatsby socket.io hot reload
    expose:
      - 3000
      - 443
      - 80
      - 3125
    tty: true
    networks:
      - the_net

volumes:
  db_data: {}
  wordpress: {}

networks:
  the_net: {}